packages:
  - 'packages/*'
  - docs
  - playground
allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true

catalog:
  '@vitest/browser-playwright': ^4.1.5
  typescript: ^6.0.3
  vite: ^8.0.13
  vitest: ^4.1.7
  '@types/node': ^25.9.1
